### ISSUE TITLE
Use/Install the  fbett/le-acme2-php

### ISSUE THREAD

**Issue by TufaVideo** [fbett/le-acme2-php#5]
I was wondering if there are any install instructions for  fbett/le-acme2-php
Most things are unclear.
I can install a tree of php files only with some trouble.
I need to know any directories used, how to set them to my local names, what they are for and how they will be used.
I do not run cron, and production site updates cannot be done from within the php/Apache system.
Need some help here ...
Target site/first try:  www.randomserver.dyndns.org

**Comment by fbett** [comment]
Hi, thanks for your interests in this library.

The propose of this library is to integrate it in a web server management tool.
But of course, it also possible to use it as a standalone.

Could you explain me, why it is not possible to update the web server configuration by a script?

You have to know, that the Lets Encrypt SSL Certificates are free of charge on the one side, but because of that, the certificates are only valid for a short time (three months).

As it would be annoying to update the web server configuration each time manually, there are a lot of ways to update the web server configuration automatically. 
This library helps to fetch the certificates, but does not configure the web server itself. The benefit of using this library is, it could be easily integrated.

There are also some Lets Encrypt clients, which will fetch the certificates and will configure the web server, but these clients can not be integrated easily.

**Comment by TufaVideo** [comment]
I run Apache, with about 5 web pages. On Windows. 
A system script load all static html up on a RAM disk. 
Then Apache starts ... on a "User" account. This account do
not have "write" to most files.
So basically I cannot just "download" and use some button or tool.
I need to know what part of code refresh and download certificates.
I need to know what part of code is used on each html download to
start the https.
The "certificates" will go write-protect onto the RAM-disk.
Updates every second month, or so, must be off-line, and using a system account.
---
Now.
I work in encryption, and dismiss any and all idéa that any security can be obtained.
...a link ... eh ...
www.trng98.se/trng98_encryption_documents/public%20key%20cryptography%20-%20why%20it%20dont%20work%20and%20why%20you%20dont%20need%20it.pdf
... where the purpose is to obtain a key for a more conventional cipher; many are weak or cracked ...
See "System info" for a list of so-called "supported" ciphers.
-------
So I intend to read the php code, to see if I can understand what it does.
If I get it to work, there will be a list of tricks and install instructions collected on the way.
I must manually install each and every php.
I cannot get any security, and I most likely don't need any. But fun if it "works".
Best regards!

**Comment by TufaVideo** [comment]
Cannot format the text ..

**Comment by fbett** [comment]
Ok, there could be an issue: this library is not tested to be used with Windows.
Also the introduction ("README.md") requires a (L)UNIX-System.

So, i suggest to take a look on the clients, tested with windows:
https://letsencrypt.org/docs/client-options/
